Repository TeamGuu/teamguu-backend, pull requests merged in 2023-04, with the labels that each got.

#2 [ feat ] : 엔티티 생성
  src/main/java/teamguu/backend/domain/matchinginfo/entity/MatchingInfo.java
  src/main/java/teamguu/backend/domain/matchinginfo/entity/Status.java
  src/main/java/teamguu/backend/domain/matchinginfo/repository/MatchingInfoRepository.java
  src/main/java/teamguu/backend/domain/member/entity/Member.java
  src/main/java/teamguu/backend/domain/reservationinfo/entity/ReservationInfo.java
  src/main/java/teamguu/backend/domain/reservationinfo/repository/ReservationInfoRepository.java
  src/main/java/teamguu/backend/domain/stadium/entity/Stadium.java
  src/main/java/teamguu/backend/domain/stadium/repository/StadiumRepository.java
  src/main/java/teamguu/backend/domain/team/entity/Sports.java
  src/main/java/teamguu/backend/domain/team/entity/Team.java
  src/main/java/teamguu/backend/domain/team/repository/TeamRepository.java
Labels: enhancement

#10 Feat/#5 팀생성, 팀정보가져오기
  src/main/java/teamguu/backend/config/openapi/OpenApiConfig.java
  src/main/java/teamguu/backend/config/security/SecurityConfig.java
  src/main/java/teamguu/backend/domain/member/dto/sign/LoginRequestDto.java
  src/main/java/teamguu/backend/domain/member/dto/sign/SignUpRequestDto.java
  src/main/java/teamguu/backend/domain/member/entity/Member.java
  src/main/java/teamguu/backend/domain/member/service/MemberService.java
  src/main/java/teamguu/backend/domain/team/controller/TeamController.java
  src/main/java/teamguu/backend/domain/team/dto/CreateTeamRequestDto.java
  src/main/java/teamguu/backend/domain/team/dto/SimpleTeamInfoResponseDto.java
  src/main/java/teamguu/backend/domain/team/dto/TeamInfoResponseDto.java
  src/main/java/teamguu/backend/domain/team/entity/Sports.java
  src/main/java/teamguu/backend/domain/team/repository/TeamRepository.java
  src/main/java/teamguu/backend/domain/team/service/TeamService.java
  src/main/java/teamguu/backend/exception/ExceptionAdvice.java
  src/main/java/teamguu/backend/exception/situation/TeamNameAlreadyExistsException.java
  src/main/java/teamguu/backend/exception/situation/TeamNotFoundException.java
  src/main/java/teamguu/backend/response/SuccessMessage.java
Labels: feat

#8 [ feat ] 로그아웃 구현
  src/main/java/teamguu/backend/config/security/SecurityConfig.java
  src/main/java/teamguu/backend/domain/member/controller/AuthController.java
  src/main/java/teamguu/backend/domain/member/dto/sign/LogoutRequestDto.java
  src/main/java/teamguu/backend/domain/member/service/AuthService.java
  src/main/java/teamguu/backend/domain/member/service/MemberService.java
Labels: feat

#14 S3 세팅과 팀 로고 이미지 변경 API 구현
  build.gradle
  src/main/java/teamguu/backend/config/aws/AmazonS3Config.java
  src/main/java/teamguu/backend/config/aws/AmazonS3Service.java
  src/main/java/teamguu/backend/domain/member/controller/AuthController.java
  src/main/java/teamguu/backend/domain/team/controller/TeamController.java
  src/main/java/teamguu/backend/domain/team/dto/CreateTeamRequestDto.java
  src/main/java/teamguu/backend/domain/team/entity/Team.java
  src/main/java/teamguu/backend/domain/team/service/TeamService.java
  src/main/java/teamguu/backend/exception/ExceptionAdvice.java
  src/main/java/teamguu/backend/exception/situation/EmptyFileException.java
  src/main/java/teamguu/backend/response/SuccessMessage.java
Labels: feat

#15 [ feat ] 매칭
  src/main/java/teamguu/backend/config/aws/AmazonS3Config.java
  src/main/java/teamguu/backend/config/aws/AmazonS3Service.java
  src/main/java/teamguu/backend/config/security/SecurityConfig.java
  src/main/java/teamguu/backend/domain/matchinginfo/controller/MatchingInfoController.java
  src/main/java/teamguu/backend/domain/matchinginfo/dto/CreateMatchingInfoRequestDto.java
  src/main/java/teamguu/backend/domain/matchinginfo/dto/MatchingInfoResponseDto.java
  src/main/java/teamguu/backend/domain/matchinginfo/dto/SimpleMatchingInfoResponseDto.java
  src/main/java/teamguu/backend/domain/matchinginfo/entity/MatchingInfo.java
  src/main/java/teamguu/backend/domain/matchinginfo/entity/Status.java
  src/main/java/teamguu/backend/domain/matchinginfo/repository/MatchingInfoRepository.java
  src/main/java/teamguu/backend/domain/matchinginfo/service/MatchingInfoService.java
  src/main/java/teamguu/backend/domain/team/controller/TeamController.java
  src/main/java/teamguu/backend/domain/team/dto/SimpleTeamInfoResponseDto.java
  src/main/java/teamguu/backend/domain/team/repository/TeamRepository.java
  src/main/java/teamguu/backend/domain/team/service/TeamService.java
  src/main/java/teamguu/backend/exception/ExceptionAdvice.java
  src/main/java/teamguu/backend/exception/situation/MatchingInfoNotFoundException.java
  src/main/java/teamguu/backend/response/SuccessMessage.java
Labels: feat

#19 [ feat ] 내 프로필 정보, 팀 정보 수정
  src/main/java/teamguu/backend/domain/member/controller/AuthController.java
  src/main/java/teamguu/backend/domain/member/controller/MemberController.java
  src/main/java/teamguu/backend/domain/member/dto/member/EditMemberInfoRequestDto.java
  src/main/java/teamguu/backend/domain/member/entity/Member.java
  src/main/java/teamguu/backend/domain/member/service/AuthService.java
  src/main/java/teamguu/backend/domain/member/service/MemberService.java
  src/main/java/teamguu/backend/domain/team/controller/TeamController.java
  src/main/java/teamguu/backend/domain/team/dto/EditTeamInfoRequestDto.java
  src/main/java/teamguu/backend/domain/team/entity/Team.java
  src/main/java/teamguu/backend/domain/team/service/TeamService.java
  src/main/java/teamguu/backend/response/SuccessMessage.java
Labels: feat

#21 S3 연결
  src/main/java/teamguu/backend/config/aws/AmazonS3Config.java
  src/main/java/teamguu/backend/config/aws/AmazonS3Service.java
  src/main/java/teamguu/backend/domain/member/controller/MemberController.java
  src/main/java/teamguu/backend/domain/member/repository/MemberRepository.java
  src/main/java/teamguu/backend/domain/member/service/MemberService.java
  src/main/java/teamguu/backend/domain/team/controller/TeamController.java
  src/main/java/teamguu/backend/domain/team/service/TeamService.java
  src/main/resources/application.yml
Labels: enhancement, feat

#23 [ fix ] 팀 정보 수정 예외 처리
  src/main/java/teamguu/backend/domain/team/dto/EditTeamInfoRequestDto.java
  src/main/java/teamguu/backend/domain/team/service/TeamService.java
Labels: bug

#25 1차 배포 전 리팩토링
  src/main/java/teamguu/backend/domain/matchinginfo/controller/MatchingInfoController.java
  src/main/java/teamguu/backend/domain/matchinginfo/service/MatchingInfoService.java
  src/main/java/teamguu/backend/domain/member/controller/AuthController.java
  src/main/java/teamguu/backend/domain/member/controller/MemberController.java
  src/main/java/teamguu/backend/domain/member/service/AuthService.java
  src/main/java/teamguu/backend/domain/member/service/MemberService.java
  src/main/java/teamguu/backend/domain/team/dto/CreateTeamRequestDto.java
  src/main/java/teamguu/backend/domain/team/service/TeamService.java
Labels: refactor
