Repository TeamGuu/teamguu-backend, pull requests merged in 2023-05, with the labels that each got.

#31 현재 멤버 정보 가져오기
  src/main/java/teamguu/backend/domain/member/controller/MemberController.java
  src/main/java/teamguu/backend/domain/member/dto/member/GetMemberInfoResponseDto.java
  src/main/java/teamguu/backend/domain/member/service/MemberService.java
  src/main/java/teamguu/backend/response/SuccessMessage.java
Labels: feat

#36 Fix: web cors error
  src/main/java/teamguu/backend/config/security/CorsConfig.java
  src/main/java/teamguu/backend/config/security/SecurityConfig.java
  src/main/java/teamguu/backend/config/security/WebConfig.java
Labels: fix

#38 [#37] Fix: Paging MatchingInfo & Deploy env
  docker-compose-prod.yml
  src/main/java/teamguu/backend/domain/matchinginfo/repository/MatchingInfoRepository.java
  src/main/java/teamguu/backend/domain/matchinginfo/service/MatchingInfoService.java
  src/main/java/teamguu/backend/domain/team/controller/TeamController.java
  src/main/java/teamguu/backend/domain/team/repository/TeamRepository.java
  src/main/java/teamguu/backend/domain/team/service/TeamService.java
  src/main/resources/application-prod.yml
Labels: fix

#41 [#40] Feat: create flyway db
  build.gradle
  src/main/resources/application-prod.yml
  src/main/resources/db/migration/V1__init.sql
Labels: feat

#45 [#39] Feat: Reservation CRD API
  src/main/java/teamguu/backend/domain/reservationinfo/controller/ReservationController.java
  src/main/java/teamguu/backend/domain/reservationinfo/dto/ReservationInfoResponseDto.java
  src/main/java/teamguu/backend/domain/reservationinfo/dto/ReserveRequestDto.java
  src/main/java/teamguu/backend/domain/reservationinfo/entity/ReservationInfo.java
  src/main/java/teamguu/backend/domain/reservationinfo/repository/ReservationInfoRepository.java
  src/main/java/teamguu/backend/domain/reservationinfo/service/ReservationInfoService.java
  src/main/java/teamguu/backend/domain/stadium/dto/StadiumInfoResponseDto.java
  src/main/java/teamguu/backend/domain/stadium/service/StadiumService.java
  src/main/java/teamguu/backend/exception/ExceptionAdvice.java
  src/main/java/teamguu/backend/exception/situation/ReservationInfoNotFondException.java
  src/main/java/teamguu/backend/response/SuccessMessage.java
Labels: feat

#47 [#46] Refactor: Focus on naming, before release V1.2.0
  src/main/java/teamguu/backend/config/openapi/OpenApiConfig.java
  src/main/java/teamguu/backend/domain/matchinginfo/controller/MatchingInfoController.java
  src/main/java/teamguu/backend/domain/matchinginfo/dto/MatchingInfoResponseDto.java
  src/main/java/teamguu/backend/domain/matchinginfo/dto/SimpleMatchingInfoResponseDto.java
  src/main/java/teamguu/backend/domain/matchinginfo/entity/MatchingInfo.java
  src/main/java/teamguu/backend/domain/member/controller/AuthController.java
  src/main/java/teamguu/backend/domain/member/dto/member/GetMemberInfoResponseDto.java
  src/main/java/teamguu/backend/domain/member/dto/sign/TokenRequestDto.java
  src/main/java/teamguu/backend/domain/member/service/MemberService.java
Labels: refactor

#50 [#49] Refactor: Schema
  docker-compose-prod.yml
  src/main/resources/application-prod.yml
Labels: refactor

#53 [#52] Fix: Deploy with front
  docker-compose-prod.yml
  src/main/java/teamguu/backend/config/openapi/OpenApiConfig.java
  src/main/java/teamguu/backend/config/security/CorsConfig.java
  src/main/java/teamguu/backend/config/security/SecurityConfig.java
  src/main/java/teamguu/backend/config/security/WebConfig.java
  src/main/resources/application-prod.yml
Labels: fix

#57 [#55] Bug: Validate duplicate stadium reservation
  src/main/java/teamguu/backend/domain/match/dto/GetChatMemberInfoResponseDto.java
  src/main/java/teamguu/backend/domain/member/controller/AuthController.java
  src/main/java/teamguu/backend/domain/member/service/AuthService.java
  src/main/java/teamguu/backend/domain/reservation/service/ReservationService.java
  src/main/java/teamguu/backend/exception/ExceptionAdvice.java
  src/main/java/teamguu/backend/exception/situation/ReservationAlreadyExistsException.java
Labels: bug
